# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Marcos Leal
title: XAI - eXplainable AI
email: marcossilva_604@yahoo.com.br
description:
  pt: Um blog dedicado a discussão de tópicos diversos de Ciência dos Dados e Inteligência Artificial
  en: A blog dedicated to discuss topics related to Data Science and Artificial Intelligence
index:
  en: en/index.html
  pt: 
tags_dir:
  en: /en/tags
  pt: /tags
about_dir:
  en: /en/about-me
  pt: /sobre-mim
feed:
  en: /feed-en.xml
  pt: /feed-pt.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcossilva.github.io" # the base hostname & protocol for your site
twitter_username: marcospedro
twitter:
  username: marcospedro
  card: summary
social:
  name: Marcos Leal
  links:
    - https://twitter.com/marcospedro
    - https://www.facebook.com/marcospedroleal
    - https://www.linkedin.com/in/marcospedroleal
    - https://github.com/marcossilva
github_username:  marcossilva
linkedin_username: marcospedroleal
instagram_username: marcospedroleal
facebook_username: marcospedroleal
telegram_username: mleal

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
